version: "2"

linters:
    enable:
        - errcheck
        - govet
        - staticcheck
        - unused
        - ineffassign
        - misspell

formatters:
    enable:
        - gofumpt

run:
    timeout: 3m
